# Generated by Django 3.2 on 2021-05-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(default=None, max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=300)),
                ('genre', models.CharField(default=None, max_length=300)),
                ('artist', models.URLField(default=None)),
                ('tracks', models.URLField(default=None)),
                ('Self', models.URLField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(default=None, max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=300)),
                ('age', models.IntegerField(default=None)),
                ('albums', models.URLField(default=None)),
                ('tracks', models.URLField(default=None)),
                ('Self', models.URLField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(default=None, max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=300)),
                ('duration', models.FloatField(default=None)),
                ('times_played', models.IntegerField(default=None)),
                ('artist', models.URLField(default=None)),
                ('album', models.URLField(default=None)),
                ('Self', models.URLField(default=None)),
            ],
        ),
    ]
