# Generated by Django 3.2 on 2021-05-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='track',
            name='album_id',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='track',
            name='artist_id',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
