# Generated by Django 3.2 on 2021-05-03 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareapp', '0003_auto_20210502_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareapp.artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareapp.album'),
        ),
    ]
